Code Review
alexisuwimana/Admission-trials-code-review pull request #1
Opened 2021-10-28 17:42 UTC by alexisuwimana

add files to my repository

2021-10-28 17:53 UTC, alexisuwimana commented on css/style.css
> +}
**REQUEST FOR CHANGES**

Good job so far your code is clean but if you can make some changes might be done like removing space before the bracket.

2021-10-28 17:53 UTC, alexisuwimana commented on css/style.css
> +}
you did  a great job but you need to use linters to check you code if are clear na d on standard

2021-10-28 17:59 UTC, GzimAsani requested changes
# Hi @alexisuwimana                                     
Good job so far! Your code looks fine, good job :+1:  :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good job using inline comments

## Required Changes ♻️ 
- [ ] _Check inline comments for more information :arrow_double_down:_ 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-28 17:59 UTC, GzimAsani commented on css/style.css
> +}
- [ ] Try to rewrite this comment and ask it more politely just like you did in the first comment
- [ ] Use something similar to my template first letting the student know what they did good and then requesting the changes in the comments

2021-10-28 19:08 UTC, mikethreels requested changes
Hi Alexis, 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-28 19:08 UTC, mikethreels commented on css/style.css
> +}
- [ ] a good start on your code review 👍 however as the previous CR mentioned please rewrite the comment and ask it more politely.

2021-10-29 16:32 UTC, alexisuwimana commented on css/style.css
> +}
**REQUEST FOR CHANGES**

Good job so far your code is clean but if you can make some changes might be done like removing space before the bracket.

2021-10-29 16:32 UTC, alexisuwimana commented on index.html
> +
**Change Required**

nice job so far but I suggest you do some changes to remove space between two div in order to have clean code for other

2021-10-29 16:32 UTC, alexisuwimana commented on css/style.css
> +    color: white;
**REQUEST FOR CHANGES** 

Good job so far your code is clean but if you can make some changes might be done like removing space before the bracket.

2021-10-29 16:37 UTC, helman101 commented
# STATUS: APPROVED 🟢 🥳 

Hi @alexisuwimana 🥇 , 

### Congratulations!!! 🥳 🎉

You have successfully completed all the expectations for this project, there is nothing more to do here, now you can go on your way and keep improving your skills.

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 18:16 UTC, merged